OWNERS
Adds the AWS team as reviewers and approvers for the AWS cloud provider.
/kind cleanup
/sig aws
=> Add AWS team as owners

pkg/cloudprovider/providers/aws/BUILD, pkg/cloudprovider/providers/aws/OWNERS, pkg/cloudprovider/providers/aws/aws.go, pkg/cloudprovider/providers/aws/aws_fakes.go, pkg/cloudprovider/providers/aws/aws_instancegroups.go, pkg/cloudprovider/providers/aws/aws_loadbalancer.go, pkg/cloudprovider/providers/aws/aws_loadbalancer_test.go, pkg/cloudprovider/providers/aws/aws_metrics.go, pkg/cloudprovider/providers/aws/aws_routes.go, pkg/cloudprovider/providers/aws/aws_test.go, pkg/cloudprovider/providers/aws/aws_utils.go, pkg/cloudprovider/providers/aws/device_allocator.go, pkg/cloudprovider/providers/aws/device_allocator_test.go, pkg/cloudprovider/providers/aws/instances.go, pkg/cloudprovider/providers/aws/instances_test.go, pkg/cloudprovider/providers/aws/log_handler.go, pkg/cloudprovider/providers/aws/regions.go, pkg/cloudprovider/providers/aws/regions_test.go, pkg/cloudprovider/providers/aws/retry_handler.go, pkg/cloudprovider/providers/aws/retry_handler_test.go, pkg/cloudprovider/providers/aws/sets_ippermissions.go, pkg/cloudprovider/providers/aws/tags.go, pkg/cloudprovider/providers/aws/tags_test.go, pkg/cloudprovider/providers/aws/volumes.go
Copies the latest version of the AWS cloud provider from kubernetes/kubernetes@0df79e4daa into this package. Future maintenance will occur here and patches from in-tree updates will be applied regularly to keep the code-bases in sync.
There is nothing that needs detailed review in this commit as the code was copied completely unmodified from kubernetes/kubernetes.
/cc @d-nishi 
/milestone v1.13
/kind feature
/sig aws
=> Copy latest version of in-tree provider

CHANGELOG.md, changelogs/CHANGELOG-0.1.md
This adds the changelog for the alpha v0.1.0 release. The hashes are provisional based on my fork as I don't yet have access to create tags in this repo.
/milestone v1.13
/kind feature
/sig aws
/assign @d-nishi
=> Add changelog for v0.1.0

README.md
In `README.md` Master policy section trailing section had a `'` (comma). If you don't have multiple section this code be syntax issue for json.
=> removed trailing comma from Master policy in README.md

cmd/aws-cloud-controller-manager/main.go
This fixes the failing tests in https://github.com/kubernetes/cloud-provider-aws/pull/34#issuecomment-474662159
/assign @spiffxp @gnufied 
```release-note
NONE
```
=> Use canonical import path for cloud-provider-aws

README.md, cmd/aws-cloud-controller-manager/main.go
Due to copy-paste from the external cloud controller manager code, some
of the comments in cmd/aws-cloud-controller-manager/main.go were
outdated, so this patch makes those comments specific to the AWS cloud
provider. Also removes a note in the README that no longer applies now
that the cloud-provider-aws code has been split out from k/k.
```release-note
NONE
```
=> small fixups to README and a-c-c-m comments

README.md
I noticed in the Kubernetes events that the cloud controller was
unable to DeregisterTargets and had to add the permission in order
to resolve this.
```
(combined from similar events): Error updating load balancer with new hosts map[ip-10-222-240-110.eu-west-1.compute.internal:{} ip-10-222-240-126.eu-west-1.compute.internal:{} ip-10-222-240-35.eu-west-1.compute.internal:{} ip-10-222-240-38.eu-west-1.compute.internal:{} ip-10-222-240-39.eu-west-1.compute.internal:{} ip-10-222-240-42.eu-west-1.compute.internal:{} ip-10-222-240-9.eu-west-1.compute.internal:{}]: error trying to deregister targets in target group: "AccessDenied: User: arn:aws:sts::139377770564:assumed-role/k8s-prod-v1-master/i-0671e0b9a7cfc …
```
=> Add missing elasticloadbalancing:DeregisterTargets IAM permission

Dockerfile
/kind feature
Containerizes the aws-cloud-controller-manager binary so that it can be run from Docker. Mostly a copy from [cloud-provider-vsphere](https://github.com/kubernetes/cloud-provider-vsphere/blob/master/cluster/images/controller-manager/Dockerfile).
```release-note
NONE
```
=> add dockerfile for containerization

.gitignore, README.md, hack/local-up-cluster.sh
/kind feature
This PR adds a local-up-cluster script for bringing up a single node cluster on an AWS EC2 instance. The benefit is to allow new developers to easily set up a single node cluster on EC2 for developing and debugging the aws-cloud-provider. 
Feel free to make any suggestions as to any additional setup steps should be included for this script.
I figured this would be a "test" kind of PR. Not really a real "feature". 
NONE
=> Add local-up-cluster script for testing the aws cloud provider

manifests/aws-cloud-controller-manager-daemonset.yaml, manifests/rbac.yaml
/kind feature
Adds sample manifests for running the aws-cloud-controller-manager. Note the image is stubbed out for now until we have a public container image. 
```release-note
NONE
```
=> Add sample manifests for aws-cloud-controller-manager

docs/book/README.md, docs/book/SUMMARY.md, hack/build-gitbooks.sh, netlify.toml
This PR contains the bare minimum Netlify configuration for setting up a [subproject site](https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md).
Some discussion pending on what the content will look like but figured we can get the site plumbing done prior to that.   
Part of https://github.com/kubernetes/cloud-provider-aws/issues/86 and https://github.com/kubernetes/cloud-provider-aws/issues/42
```release-note
NONE
```
=> add initial gitbooks configuration for documentation site

OWNERS
/kind cleanup
Currently going through subproject OWNER files under SIG Cloud Provider and moving approvers that have been inactive for more than 1 year to emeritus status.
I'm going to time box this PR til May 15th (next Provider AWS meeting) in case any of the approvers express interest in contributing to the project. 
Fixes #
```release-note
NONE
```
=> move inactive approvers to emeritus_approvers

Makefile
/kind feature
Add new make targets for building and pushing cloud-controller-manager images to the new staging GCR repo. 
Fixes #
```release-note
NONE
```
=> Add make targets for pushing to staging GCR repo

cmd/aws-cloud-controller-manager/main.go, pkg/providers/v1/install.go, pkg/providers/v2/interface.go
/kind feature
Adds an initial implementation of an experimental v2 provider that is exclusively out-of-tree. The actual implementation is incomplete, this just adds the initial boilerplate code for the cloud provider interface. Future PRs will incrementally implement the entire interface.
There are many requested features about the existing AWS cloud provider that are difficult to implement since we can't break behavior against existing clusters. Some of these include but are not limited to:
* allowing node names that are not the ec2 private DNS
* better naming of ELB/NLB resources
In addition, the existing provider is catered towards the deprecated in-tree …
=> add initial experimental v2 AWS cloud provider

docs/book/SUMMARY.md, docs/book/getting_started.md, docs/book/known_limitations.md, docs/book/prerequisites.md, docs/book/service_loadbalancers.md
We're trying to improve documentation on the AWS cloud provider. Before divvying up the work, I would like agreement on what the content should look like at a high level. I've added some initial sections that I think is worth covering, I'd like to use this PR to discuss what other content we should include.
```release-note
NONE
```
=> Add initial sections for docs site

go.mod, pkg/providers/v2/cloud.go, pkg/providers/v2/cloud_test.go
/kind feature
This PR creates a new instance of aws cloud, which helps future PRs to commit in parallel with fewer conflicts
Part of #125
```release-note
Create a new instance of aws cloud of v2 provider.
```
=> Create a new instance of aws cloud

manifests/aws-cloud-controller-manager-daemonset.yaml
/kind cleanup
Latest tag is v1.19.0-alpha.1, not v1.19.1-alpha.1, our example manifests should reflect that.
Fixes #
```release-note
NONE
```
=> latest manifest should point to v1.19.0-alpha.1, not v1.19.1-alpha.1

README.md
README still states that `--cloud-provider` flag *shouldn't* be passed to aws-cloud-controller-manager, which is not the case anymore. This PR updates that section.
```release-note
NONE
```
=> Update Flags section of README

Makefile, cloudbuild.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
We want to build and push containers using prow post-submits.  This is a first pass at a script that takes care of tag format validation and passing GCR credentials to docker.  Simplified version of the vsphere cloud provider release.sh script and makefile.  
Fixes #135
```release-note
NONE
```
=> Makefile target to build and push image for release

Dockerfile, Makefile, cloudbuild.yaml
- Remove cloudbuild logic from Makefile
- Fix ldflags version
- Use gcr.io/cloud-builders/docker for cloudbuild
(tangentially, this should also fix the cloudbuild
build, which was failing because of what appeared
to be an env var collision between the Makefile
and the build container with $IMAGE).
>
/kind cleanup
Simplifies cloudbuild and Makefile (should fix it in the process, but we will need to merge it to see).  
Fixes #
```release-note
NONE
```
=> Fix cloudbuild and simplify Makefile & cloudbuild

cmd/aws-cloud-controller-manager/main.go
pass the value from `--cloud-config` flag for reading the **clusterName** value
initialize cloud provider with the cloud provider name and config file provided
/kind feature
Fixes #
```release-note
NONE
```
=> Pass in cloud config file to initialize cloud provider

.github/workflows/publish_docs.yml, docs/book/README.md, docs/book/getting_started.md, docs/book/index.md, mkdocs.yml
- Migrates the docs from gitbook to mkdocs because gitbook is deprecated. Here's what the new docs looks like: https://ayberk.github.io/cloud-provider-aws/
- Adds a new github action to deploy docs automatically when they're updated
**PS**: `mkdocs` doesn't builds the site into the root folder, so we'll have to change the folder for Github Pages to `/` (from repo settings).
I'll delete the gitbook related stuff on a different PR. If I delete the netlify.toml, checks fail.
```release-note
NONE
```
=> Migrate to mkdocs

go.mod, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_instancegroups.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_loadbalancer_test.go, pkg/providers/v1/aws_metrics.go, pkg/providers/v1/aws_routes.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/aws_utils.go, pkg/providers/v1/device_allocator.go, pkg/providers/v1/device_allocator_test.go, pkg/providers/v1/doc.go, pkg/providers/v1/instances.go, pkg/providers/v1/instances_test.go, pkg/providers/v1/log_handler.go, pkg/providers/v1/retry_handler.go, pkg/providers/v1/retry_handler_test.go, pkg/providers/v1/sets_ippermissions.go, pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go, pkg/providers/v1/volumes.go
/kind cleanup
Fixes #
This copies the v1 provider to the local v1 directory.  This merge needs to be coordinated with an effort to stop accepting features into k/k (legacy-cloud-providers).
I was working off https://github.com/kubernetes/cloud-provider-aws/pull/151 (so those commits show up here too) as I am expecting us to get that in first, but I can separate this if for some reason we want this to merge first.
```release-note
The V1 AWS provider has been rehomed from `legacy-cloud-providers` to `cloud-provider-aws/pkg/providers/v1`
```
=> Merge legacy provider

README.md
>
> /kind bug
> /kind design
> /kind flake
Updated 1st page documentation to include released versions and context around the different code users might be interested in when navigating to this repository. 
Fixes #
/cc @wongma7 @ayberk @andrewsykim 
```release-note
None
```
=> Add released versions to README

docs/book/credential_provider.md, docs/book/index.md, mkdocs.yml
Adds documentation for the new ECR credential provider. I tried to explain how to use it and also provided an example configuration that should satisfy the general use case.
Rendered docs can be seen here: https://ayberk.github.io/cloud-provider-aws/credential_provider/
```release-note
NONE
```
=> Add documentation for cred provider

hack/changelog.py
Adds a script to generate changelog between two tags. Example output between v1.19 tag and HEAD:
```
➜  cloud-provider-aws git:(changelog_script) ✗ 02/19 14:14 python3 hack/changelog.py --token $TOKEN --print-only --section-title Release --range v1.19.0-alpha.1.. 
Release
* Replace book homepage with README ([#176](https://github.com/kubernetes/cloud-provider-aws/pull/176), @ayberk)
* update klog library from 2.4.0 to 2.5.0 ([#170](https://github.com/kubernetes/cloud-provider-aws/pull/170), @dineshkumar181094)
* Add documentation for cred provider ([#174](https://github.com/kubernetes/cloud-provider-aws/pull/174), @ayberk)
* Add released versions to README …
```
=> Add script to generate changelog

.github/workflows/release.yaml
/kind feature
It adds a workflow that creates a github release whenever a version tag is pushed.
An example can be seen [here](https://github.com/ayberk/cloud-provider-aws/releases/tag/v-test).
```release-note
NONE
```
=> Add release github workflow

.github/cr.yaml, .github/workflows/helm_chart_release.yaml, charts/aws-cloud-controller-manager/Chart.yaml, charts/aws-cloud-controller-manager/Readme.md
/kind feature
- Helm chart releaser action will release a new chart whenever charts folder is updated on master branch.
- We will start hosting our chart index on gh-pages, so installation will be much simpler. I updated the helm README with the new commands.
Fixes #188
I tested and verified on my fork that it works.
```release-note
NONE
```
=> Automate helm chart release

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/99130
---
Use GA topoogy labels for EBS
/kind cleanup
```release-note
NONE
```
=> Cherry-pick: Use GA topoogy labels for EBS (#99130)

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/99664
---
delete leaked volume if driver don't know the volume status -- aws
/kind bug
```release-note
NONE
```
=> Cherry-pick: delete leaked volume if driver don't know the volume status -- aws (#99664)

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/97431
---
* support subnets without cluster tag for auto-discovery
* add support for manual subnet configuration via service annotation
/kind feature
```release-note
NONE
```
=> Cherry-pick: additional subnet configuration for AWS ELB (#97431)

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/instances.go, pkg/providers/v1/instances_test.go
/kind feature
This PR adds support for adding Fargate worker nodes to Kubernetes cluster. To add Fargate worker nodes, node providerID should have the prefix "fargate-" followed by ENI IP address..
This code doesn't change anything for EC2 worker nodes and only performs Describe interface for Fargate worker nodes.
```release-note
Adds support for worker nodes based on ENI
```
=> Add ENI support for nodes(for Fargate nodes)

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
/kind feature
/priority important-longterm
IPv6 support has been around for some time now both in AWS and Kubernetes. [Dual-Stack](https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#ipv4-ipv6-dual-stack-support) is also one of the major themes in Kubernetes 1.21.
I am trying to add IPv6 support for kOps and bumping into various issues because the IPv6 addresses are not returned by the cloud provider implementation.
xRef: https://github.com/kubernetes/kops/issues/8432
I am not sure if there was any reason for not implementing this until now, but this PR should be a good conversation starter.
n/a
I added the IPv6 addresses to …
=> Add support for returning IPv6 node addresses

pkg/providers/v1/aws.go
CCM builds its own credential providers list and configures them directly instead of using those from the session.
This PR checks the presence of the web identity env vars and adds a web identity role provider.
/kind feature
I have been working on IRSA support for the AWS CCM for kOps, and I had to add something like this in order for CCM to pick up the AWS credentials. Without this, it would just use the instance role, which no longer has the necessary AWS permissions to run CCM.
```release-note
Cloud Controller Manager can now consume credentials through web identity role credentials.
```
=> Add support for consuming web identity credentials

hack/cherry-pick-kk.sh
Until legacy-cloud-provider is deleted, there is a possibility that
bug fixes are merged into k/k before this respository. This script
makes it easier to cherry-pick commits from there to here, which
requires a path rewrite and is a pain to do by hand.  This will
probably stop being useful if the v1 provider in this repository
diverges from the legacy provider in k/k, and we should encourage
contributions to come here first.
/kind cleanup
Quick script to facilitate cherry picking and path rewriting from k/k
```release-note
NONE
```
=> Add script to facilitate cherry-picking from k/k

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Many pods (e.g metrics-server) will always pick the first InternalIP regardless of the family the pod itself has. This will break for any pod not running on host network if the Pod only has an ipv6 address.
This PR will make which IP families to add to Node objects configurable through cloud config.
```release-note
IP families added to Node objects are now configurable though cloudconfig. The default configuration is ipv4 only.
```
=> Make Node IP families configurable

pkg/providers/v1/sets_ippermissions.go
/kind bug
Looking through the code in this function, it seems that we are iterating through the list three times to unpack it, but in the second iteration, we are appending to the wrong list, meaning that the input to the 3rd iteration can be wrong when a particular permission has more than one GroupPair associated with it.
This was picked up by a code scanner, and seemed like a simple enough change that I should propose it
```release-note
NONE
```
=> Fix copy/paste error in IPPermissionSet.Ungroup

OWNERS
Remove inactive approvers and add @jaypipes, who is an active Kubernetes community member and contributer/maintainer of [AWS Controllers for Kubernetes (ACK)](https://github.com/aws-controllers-k8s/community/graphs/contributors) and a member of the EKS development team.
```release-note
NONE
```
=> Remove inactive and add jaypipes

pkg/providers/v1/sets_ippermissions_test.go
>
/kind cleanup
Add a test for `sets_ippermissions_test.go` which is had a bug that is fixed in https://github.com/kubernetes/cloud-provider-aws/pull/250.
merge https://github.com/kubernetes/cloud-provider-aws/pull/250 first.
```release-note
NONE
```
=> Add a unit test for sets_ippermissions

charts/aws-cloud-controller-manager/values.yaml, manifests/base/aws-cloud-controller-manager-daemonset.yaml
>
/kind cleanup
We recently started promoting the tagged ccm images to k8s-artifacts-prod so we should use those instead of the images in k8s-staging-provider-aws.  See [k8s-artifacts-prod](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/provider-aws/cloud-controller-manager?tab=vulnz) for the list of promoted images. 
Fixes https://github.com/kubernetes/cloud-provider-aws/issues/228
**Special notes for your reviewer**: 
* Supersedes https://github.com/kubernetes/cloud-provider-aws/pull/245
* Wait for https://github.com/kubernetes/k8s.io/pull/2667
```release-note
NONE
```
=> Use promoted images

pkg/providers/v1/aws.go
* EC2 pagination doesn't work if MaxResults is not set
* Only set if InstanceIds isn't set.
>
/kind bug
The describeInstances API doesn't paginate unless maxResults is set.  
Fixes #
/hold 
```release-note
Ensure pagination of EC2 describeInstances calls
```
=> Set MaxResults if it is not set

charts/aws-cloud-controller-manager/Chart.yaml, charts/aws-cloud-controller-manager/templates/daemonset.yaml, charts/aws-cloud-controller-manager/values.yaml
/kind cleanup
Allow helm chart users to set arbitrary flags.
Fixes #235
Replaces #236 
```release-note
All command line flags can be overridden in the helm chart.  
```
=> [helm] Command line flags can be overridden

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
* Add test for DescribeInstances (the lower level wrapper around the API call).
* Use interface in awsSdkEC2 to allow for mock.
* Check `len(request.InstanceIds) == 0` to account for both empty structs and nil pointers.
See https://github.com/kubernetes/cloud-provider-aws/pull/274 for the change and https://github.com/kubernetes/cloud-provider-aws/issues/269 for some context.  
/kind cleanup
Add a test and make a comparison more resilient. 
```release-note
NONE
```
=> Add test for DescribeInstances

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
>
/kind cleanup
Cherry pick https://github.com/kubernetes/kubernetes/pull/105361 from upstream.  This is required until we explicitly support mixed protocols in the external CCM.  
> The AWS in-tree controller doesn't support mixed protocols for service. This PR adds validation logic to the AWS cloudprovider to not provision any load balancer for service with mixed protocols so that the MixedProtocolLBService feature gate can be enabled safely on AWS.
> kubernetes/enhancements#1435
> Manually tested with feature-gate MixedProtocolLBService=true
> * services with mixed protocol do not get reconciled, …
=> validate service with mixed protocols

pkg/providers/v1/aws.go
>
/kind feature
AWS recently launched support for instance DNS host names based on instance ID rather than ipv4.
This PR adds support for nodes with those DNS hostnames
Fixes #285 
Originally, node names were suffixed with the domain name. AWS CCM is to my knowledge the only CCM that do not use only the hostnames. As a consequence, all relevant k8s components need set `--hostname-override` as kubelet et.al cannot automatically determine the hostname. Because of this, with RBN, CCM expects only the hostname. The `kubectl get nodes` output then looks like this:
```
$ kubectl get nodes
NAME …
```
=> Add support for RBN-based node names

Dockerfile, Makefile, cloudbuild.yaml
/kind feature
Adds support for ARM64 builds.
Fixes #219 
Tested using kOps in https://github.com/kubernetes/kops/pull/12895:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/12895/pull-kops-e2e-arm64/1467542201067114496
```release-note
Adds support for ARM64
```
=> Add support for ARM64 builds

Dockerfile
/kind feature
**What this PR does / why we need it**: To collect/persist logs (versus just emitting to stdout/stderr and letting container runtime deal with them) go-runner should be used. kubernetes already uses this image as base for apiserver, scheduler, and KCM https://github.com/kubernetes/kubernetes/blob/release-1.23/build/common.sh#L94. Since cloud provider is a "kubernetes component" basically split off from KCM it makes sense to use this image as base for cloud provider as well. More details are here: https://github.com/kubernetes/release/tree/master/images/build/go-runner. 
Fixes #
```release-note
NONE
```
=> Use go-runner as base image

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go
```release-note
Target groups, security groups and listeners are now tagged on creation rather than as separate API calls.
```
=> Tag on create

charts/aws-cloud-controller-manager/Chart.yaml, charts/aws-cloud-controller-manager/values.yaml, examples/existing-cluster/base/aws-cloud-controller-manager-daemonset.yaml
/kind cleanup
/hold
* Wait for https://github.com/kubernetes/k8s.io/pull/3287
* Check image is in us.gcr.io/k8s-artifacts-prod/provider-aws/cloud-controller-manager
```release-note
NONE
```
=> Update charts for v1.23.0-alpha.0

Makefile, hack/e2e/run.sh, hack/install-e2e-tools.sh
Fixes failing e2e test.
* Create test run directory earlier to avoid failure
* Install e2e prereqs
Fixes #
```release-note
NONE
```
=> Get e2e tests working in prow

pkg/providers/v1/aws.go
> kind bug
STS suggests using regional endpoints. ([source](https://docs.aws.amazon.com/general/latest/gr/sts.html))
> AWS recommends using Regional STS endpoints to reduce latency, build in redundancy, and increase session token validity.
The PR uses sts regional endpoints, fetched using the metadata, instead of global endpoints.
Fixes #
```release-note
Updates to the cloud-controller-manager to use regional endpoint instead of global endpoint, as AWS recommends using Regional STS endpoints to reduce latency, build in redundancy, and increase session token validity.
```
=> add sts regional endpoint logic

Makefile, hack/e2e/run.sh, hack/install-e2e-tools.sh
Cherry pick of #312 on release-1.22.
#312: Fix e2e failures
```release-note
NONE
```
=> Automated cherry pick of #312: Fix e2e failures

hack/e2e/run.sh
Fixes failing tests on release-1.22.
Tests are failing because the test cluster doesn't have permissions to create an untagged security group.  Tag-on-create was added recently so checking to see if kops changed permissions from 1.22 to 1.23.  If this doesn't work we can try cherry-picking https://github.com/kubernetes/cloud-provider-aws/pull/293.
```release-note
NONE
```
=> Fix 1.22 e2e failures

Makefile, pkg/providers/v1/aws.go, pkg/providers/v1/aws_routes.go, pkg/providers/v1/aws_test.go
/kind bug
**What this PR does / why we need it**: 
The function `mapInstanceToNodeName` assumes that node names are always equal to private dns names. This assumption does not always hold, specifically in 1.23 kops clusters with CCM enabled where  node names are overridden to be instance IDs.
I added `instanceIDToNodeName` as a replacement. It relies on an indexer in the node informer to find nodeName by instance ID. This solution might be heavy-handed, I don't know how expensive exactly it is to have this indexer. If we assume that node names are going to be limited to either private dns or instance ids (or fargate?) then the solution could be simpler: it could check if a node with name equal to instance id exists, as suggested here …
=> Fix route controller create/delete spam: use instanceIDToNodeName in case node name != private DNS

charts/aws-cloud-controller-manager/Readme.md, charts/aws-cloud-controller-manager/templates/daemonset.yaml, charts/aws-cloud-controller-manager/values.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Support IRSA for CCM and securityContext for additional hardening.
Fixes #327 
```release-note
chart: Expose daemonset env vars to support IRSA
```
=> Add environment and securityContexts

tests/e2e/loadbalancer.go
/kind flake
This test sometimes times out at 5 mins, especially in aws china. We just have to wait longer for the load balancer to be ready.
Fixes #
```release-note
NONE
```
=> Double load balancer timeout from 5 mins to 10

tests/e2e/loadbalancer.go
Cherry pick of #345 on release-1.23.
#345: Double load balancer timeout from 5 mins to 10
```release-note
NONE
```
=> Automated cherry pick of #345: Double load balancer timeout from 5 mins to 10

docs/TODO.md, pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go
/kind feature
**What this PR does / why we need it**: 
- Added a logic to abort work item after a certain number of retries in case EC2 responds with non-retryable errors.
- Added metrics collection to the controller.
NONE
```release-note
NONE
```
=> [Issue #325] Added retry count to abort workitem after a few failed retries

cloudbuild.yaml
>
/kind bug
> /kind design
> /kind flake
The image pushing setup in test-infra defines `_GIT_TAG` with a `vYYYYMMDD` prefix to `git describe`.
This format isn't allowed by k8s.io/component-base panicking on startup.
By trimming the date prefix from the tag, image builds will only contain the `git describe` output, matching the binaries built from the Makefile
**Which issue(s) this PR fixes**: 
Fixes #339
I copied this solution from another project's build process that also utilizes GCB and k8s.io/component-base: …
=> Trim date prefix from tag in GCB image build

cloudbuild.yaml
=> Use short git tag for version and images

cloudbuild.yaml
Cherry pick of #352 on release-1.23.
#352: Use short git tag for version and images
```release-note
```
=> Automated cherry pick of #352: Use short git tag for version and images

pkg/controllers/tagging/tagging_controller_test.go
`make test` is now successful (it was failing prior to this change).
**What this PR does / why we need it**: Fix issue with flag causing test failures
**Special notes for your reviewer**: NONE
**Does this PR introduce a user-facing change?**: 
```release-note
NONE
```
=> Fix issue with flag causing test failures in 1.22

charts/aws-cloud-controller-manager/values.yaml, docs/README.md
This PR adds a note about the AWS CCM container image. It also switches the new `registry.k8s.io` to be used as suggested by https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c/m/oD9_Q8Q9AAAJ (ref https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)).
```release-note
NONE
```
=> Add note about AWS CCM container images

Makefile
Trying to fit all go files into SOURCES overflowed bash arg max length.
Als, having these targets non-phony prevents rebuilds. Besides, we can just rely on go to do an incremental build.
/kind cleanup
```release-note
NONE
```
=> Make build targets phony

cloudbuild.yaml
Cherry pick of #376 on release-1.21.
#376: Stop tagging latest for release branches
```release-note
```
=> Automated cherry pick of #376: Stop tagging latest for release branches

pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/instances.go
* Don't tag Fargate nodes
* Label nodes to prevent retagging them again
* Increase bucket size for latency metrics
/kind bug
Fixes issues with Tagging Controller
**Special notes for your reviewer**: N/A
```release-note
Update Tagging Controller to label nodes to prevent re-tagging of the same node. This adds a new label to add nodes processed by the tagging controller.
```
=> [FIXES] [Tagging Controller] Fix issues in tagging controller

pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/instances.go
* Don't tag Fargate nodes
* Label nodes to prevent retagging them again
* Increase bucket size for latency metrics
/kind bug
Fixes issues with Tagging Controller
**Special notes for your reviewer**: N/A
```release-note
Update Tagging Controller to label nodes to prevent re-tagging of the same node. This adds a new label to nodes processed by the tagging controller.
```
=> [Cherry Pick from master to 1.22] [FIXES] [Tagging Controller] Fix issues in tagging controller

.github/workflows/tag-release.yml
To be able to check if a tag already exists, all history has to be pulled during checkout:
https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
Without this, the job will fail when the tag already exists:
https://github.com/kubernetes/cloud-provider-aws/runs/6636986249?check_suite_focus=true
Ref: #388 
/cc @olemarkus @nckturner
=> Fetch all history when tagging releases

pkg/providers/v1/aws_loadbalancer.go
In case of creating a new TG removed return dropped off  #this function
just before instance registration code. Daemon restart was needed to
call ensureTargetGroup() again and reach out registration code
(as targetGroup != nil, TG already created)
Change-Id: I57717602624d9632049596e6928ac4671387905d
/kind bug
**What this PR does / why we need it**: fix of instances registration in AWS NLB target group during its creation
Fixes #301
```release-note
NONE
```
=> Fix target group instances registration when TG created

.ko.yaml, Makefile, hack/install-ko.sh
/kind feature
The dockerx build is somewhat slow and downloads deps on every change. `ko` provides faster build and is somewhat simpler to set up and configure. We've been using ko for all image builds in kOps for some time now.
The PR also does some small fixes to the make file. Most notably, variables are not exported anymore as that broke `ko`. But we are passing in all the envs needed for the various targets anyway.
```release-note
NONE
```
=> Add make targets for building with ko

docs/prerequisites.md
A number of people try to use CCM with naming conventions that does not work (e.g `ip-xxx-xxx-xxx-xxx.my.domain`). This should make the requirements more clear.
```release-note
Document the supported node naming conventions.
```
=> Add note about node naming conventions

docs/CHANGELOG.md, docs/README.md
Changelogs for recent releases: v1.20.0, v1.21.0, v1.22.1, v1.23.1
```release-note
NONE
```
=> Changelogs

pkg/controllers/options/tagging_controller.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/controllers/tagging/tagging_controller_wrapper.go
/kind feature
**What this PR does / why we need it**: Adds rate limiting support for Tagging Controller. This helps in controlling the rate at which the controller processes items and hence control the rate at which it makes calls to services like EC2.
**Special notes for your reviewer**: N/A
```release-note
Adds rate limiting support for Tagging Controller. This helps in controlling the rate at which the controller processes items and hence control the rate at which it makes calls to services like EC2.
```
=> Add rate limiting support for Tagging Controller

hack/e2e/run.sh
This reverts commit 0b078ce702846fb1c9357496dfea2f4f46c54188.
>
Temporarily revert the trap EXIT/kops cleanup function, which is failing in the prow environment.  We do need to figure out our cleanup story but this is blocking PRs.
Fixes #445
```release-note
NONE
```
=> Revert "Ensure kops cluster is always torn down after e2e run"

hack/e2e/run.sh
Cherry pick of #451 on release-1.23.
#451: Test e2e
```release-note
```
=> Automated cherry pick of #451: Test e2e

pkg/providers/v1/aws.go, pkg/providers/v1/aws_assumerole_provider.go, pkg/providers/v1/aws_assumerole_provider_test.go
Cherry pick of #412 on release-1.23.
#412: Add rate limiting when calling STS assume role API
```release-note
```
=> Automated cherry pick of #412: Add rate limiting when calling STS assume role API

pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #448 on release-1.23.
#448: Handle InvalidInstanceID.NotFound when tagging resources
```release-note
```
=> Automated cherry pick of #448: Handle InvalidInstanceID.NotFound when tagging resources

charts/aws-cloud-controller-manager/Chart.yaml, charts/aws-cloud-controller-manager/templates/daemonset.yaml, charts/aws-cloud-controller-manager/values.yaml
/kind bug
Current helm chart in the master branch is broken. When applied to the real cluster it throws an error: `error: error validating "STDIN": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].env): invalid type for io.k8s.api.core.v1.Container.env: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false`
None
```release-note
Fixes helm chart default env in values.yaml
```
=> Fix broken helm chart

charts/aws-cloud-controller-manager/templates/daemonset.yaml, charts/aws-cloud-controller-manager/values.yaml
/kind bug
It enables setting dnsPolicy for daemonset in helm chart. In case of starting a fresh cluster all nodes have taint `node.cloudprovider.kubernetes.io/uninitialized` preventing coredns from starting (without toleration). Without coredns aws cloud provider can't resolve AWS api endpoint what leads to a locked cluster.
None
```release-note
Added possibility to control dnsPolicy through helm chart values.
```
=> Chart dns policy

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
/kind bug
The function `InstanceExistsByProviderID` returns true if the instance with the given provider id. It tries to describeENI with either `privateDNSName` or `privateIpAddress` passed in the `providerID`. For fargate use cases, the instanceID got from providerID will be like either ip-name based privateDNSName or just ip address if enableDnsSupport is set to false in a VPC. However, with resource-name based EC2 resources, privateDNSName is a different format, which has instance id instead of ip address to generate privateDNSName. This causes that `InstanceExistsByProviderID` cannot find corresponding instance. The change here is to use privateIdAddress to describeENI since this format remains same for either …
=> Use ip address to describeENI for fargate nodes

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
Cherry pick of #471 on release-1.23.
#471: Use ip address to describeENI for fargate nodes
```release-note
```
=> Automated cherry pick of #471: Use ip address to describeENI for fargate nodes

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/instances.go, pkg/providers/v1/volumes.go, pkg/providers/v2/instances.go
/kind cleanup
Currently, if a Service of type LoadBalancer is created, and `Spec.LoadBalancerSourceRanges` is not specified, the AWS cloud-provider creates one rule for the client with a source of all addresses (0.0.0.0/0).  It also create a rule per-zone for the health check.  In many cases, these health rules are subsets of the client rule with more specific CIDR blocks.
AWS Quota on `Inbound or outbound rules per security group` is defaulted to 60 with a hard max of 200 (security groups per network interface * inbound or outbound rules per security group <= 1000).
Thus, a Service of type LoadBalancer on a cluster with nodes in 3 zones will result in 4 rules being added to the security group.  This means that, for such …
=> Skip health rule creation when it is a subset of the client rule

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Cherry pick of #484 on release-1.22.
#484: Handle wrapped error for InvalidInstanceID.NotFound in
```release-note
```
=> Automated cherry pick of #484: Handle wrapped error for InvalidInstanceID.NotFound in

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
/kind bug
**What this PR does / why we need it**: Fixes https://github.com/kubernetes/cloud-provider-aws/issues/444 and hence prevents leak of node objects.
Fixes https://github.com/kubernetes/cloud-provider-aws/issues/444
**Special notes for your reviewer**: Ideally, this fix should be done [here](https://github.com/kubernetes/cloud-provider-aws/blob/1c6194aad0122ab44504de64187e3d1a7415b198/pkg/providers/v1/aws.go#L1007) by not wrapping the error but that function is exported and used in multiple places in this package as well as probably outside the package as well. Changing it there might have unintended consequences.
**Does this PR introduce a user-facing change?**: NONE
=> Handle wrapped error for InvalidInstanceID.NotFound in InstanceExistsByProviderID

pkg/providers/v1/aws_loadbalancer.go
Cherry pick of #302 on release-1.23.
#302: Fix target group instances registration when TG created
```release-note
```
=> Automated cherry pick of #302: Fix target group instances registration when TG created

go.mod, go.sum
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
Bump aws-sdk-go to v1.44.107
```release-note
NONE
```
=> Updated awd-sdk-go to v1.44.107

go.mod, go.sum
/kind cleanup
Bump aws-sdk-go to v1.44.107
```release-note
NONE
```
=> updated aws-sdk-go to v1.44.107

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
Time.Unix() returns the time in seconds so need to multiply the duration by time.Second
/kind bug
Cache duration was being calculated incorrectly (e.g. returning 21 microseconds instead of 6 hours).
Fixes #348
```release-note
NONE
```
=> Calculate cache duration correctly

hack/e2e/run.sh
>
> /kind bug
> /kind design
> /kind flake
e2e tests seem to be failing as seen in https://github.com/kubernetes/cloud-provider-aws/pull/531.
This switches the tests to use the new `--dns=none` (instead of Gossip).
In technical terms `--dns=none` means that the cluster will use the load balancer IP to set an `/etc/hosts` alias alias for the API server. This way, there is no need for extra Gossip services or Route53 DNS records.
n/a
n/a
```release-note
NONE
```
=> Run e2e tests with `--dns=none`

pkg/providers/v1/aws_loadbalancer.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
When kubernetes/kubernetes##101592 introduced the target group registration chunking, this is how the target groups were being registered. Then we would return. The rest of this function was intended to handle the case where the load balancer already exists.
#293, I believe, accidentally removed the target registration from the "create" part of this function, creating the bug #301. #302 resolved this by allowing the function to fall through to the "update" section of the code.
Since we don't need to run the checks for existing and dirty …
=> Restore chunked behaviour of target group creation in LBv2

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
>
/kind bug
> /kind design
> /kind flake
Updates the v1 provider's isRegionValid function to return an error instead of boolean. This fixes #524, where errors returned from EC2 instance metadata service were suppressed and interpreted upstream as an invalid configured region. This made it hard to track down why the provider failed. This bug appears to only be in the v1 provider.
The isRegionValid function was also renamed to validateRegion to communicate its behavior instead of a boolean check.
Fixes #524
**Does …
=> Update v1 provider isRegionValid name and to return an error

docs/credential_provider.md
/kind cleanup
This cleans up some of the documentation for the `ecr-credential-provider` command to expand on some details and fix some minor formatting in the example configuration.
```release-note
NONE
```
=> ecr-credential-provider: clean up docs

docs/prerequisites.md, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
/kind feature
Outpost, wavelength, and local zone don't support NLB or CLB at the moment. 
This pr adds check for availability zone type and includes only subnets from `availability-zone` typed zones for the auto-discovery.
Fixes #442 
I'm not sure about PR type, guess that `feature` is the most suitable one.
```release-note
Added check  for availability zone type within subnets auto-discovery procedure for a load-balancers
Auto-discovery will include only subnets from `availability-zone` typed zones.
IMPORTANT: This change requires an IAM permissions update. IAM policy for control-plane nodes
should …
```
=> Restrict subnets only to subnets from regular availability zones in ELB auto-discovery procedure

hack/e2e/run.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes e2e test failure seen in https://github.com/kubernetes/cloud-provider-aws/pull/552.
n/a
n/a
```release-note
NONE
```
=> Update kOps command for creating clusters

pkg/providers/v1/instances.go
/kind bug
This PR restricts the access to the `describeAllInstancesUncached` to a single worker. For AWS accounts with thousand of EC2 instances the call to fetch the instances from the AWS API is costly in resources. On startup of the CCM with `concurrent-service-syncs` > 1 because the cache is empty all the workers will try to hit the AWS API which creates very large spikes in resources used.
With this PR only one worker will access describeAllInstancesUncached while the rest will wait for the mutex. 
Fixes #
```release-note
Fix a bug that leads to multiple workers making concurrent …
```
=> Single goroutine access to the node cache

pkg/providers/v1/instances.go
Cherry pick of #502 on release-1.25.
#502: single update to node cache
```release-note
```
=> Automated cherry pick of #502: single update to node cache

cloudbuild.yaml
Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-aws-push-images/1633304842430582784
```
Step #2 - "cloudbuild-artifacts": == Uploading provider-aws ==
Step #2 - "cloudbuild-artifacts": gsutil -h "Cache-Control:private, max-age=0, no-transform" -m cp -n -r /workspace/_output/upload/provider-aws/*
Step #2 - "cloudbuild-artifacts": CommandException: Wrong number of arguments for "cp" command.
Step #2 - "cloudbuild-artifacts": make: *** [Makefile:201: gcs-upload] Error 1
```
/cc @dims @olemarkus @rifelpet
=> Use default GCS location to upload artifacts

Makefile
=> Don't update latest tag when uploading artifacts

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
/kind feature
This PR adds support for IPv6 Fargate nodes by assigning the right NodeInternalIP based on IP family
NONE
This code doesn't change anything for EC2 worker nodes
No
=> Add support for IPv6 Fargate nodes

.gitignore, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
The current logic derives region from the AZ with unnecessarily complex logic. As describe in #525, you can get the region directly from IMDS rather than getting it from the AZ. I've also removed the `DisableStrictZoneCheck` flag. I took an opinionated stance on this as it doesn't seem useful. It does a few things:
1. Verifies that the AWS SDK knows about the region - At first glance, this seems reasonable, but shortly after it's called, we instantiate clients in the SDK passing in the region, and if the region doesn't exist, I assume that will fail because the SDK will be unable to choose an endpoint and fail with an obvious error.
2. Gets the AZ from IMDS, again, converts it to a region and then makes …
=> Simplifies configuring provider region

docs/prerequisites.md, pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
/kind bug
This adds support for RHEL based distributions that typically use a FQDN.
Fixes #
See cloud-init for RHEL at https://github.com/canonical/cloud-init/blob/main/cloudinit/distros/rhel.py#L46
and https://github.com/canonical/cloud-init/blob/f146fe71733e72b94fad525b8cc9988b1405e760/cloudinit/distros/__init__.py#L343
```release-note
NONE
```
=> fix: handle subnets with resource based naming more flexibly

Makefile, cmd/ecr-credential-provider/main.go
/kind feature
The `ecr-credential-provider` has recently changed the API version it supports (#597). Currently, there is no straightforward way to distinguish two `ecr-credential-provider` binaries, which makes changes like #597 difficult to handle. This PR adds a `--version` flag that returns the standard `gitVersion` as in `k8s.io/component-base/version`, to help in such situations.
~~I ran `go mod vendor`, which did...a lot of things. Should I back those changes out?~~ Removed.
Yes.
```release-note
A `--version` flag has been added to the `ecr-credential-provider`.
```
=> Add version flag to ecr-credential-provider

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
>
/kind bug
If for some reason provider id of the node is updated to a invalid format, cloud provider should ignore the node instead of panic and crashing.
Fixes #604 
```release-note
NONE
```
=> ignore invalid providerid for cache indexer

cmd/ecr-credential-provider/plugin_test.go
should use out.String() instead of string(out.Bytes())
Fixes #
```release-note
NONE
```
=> chore: use out.String() instead of string(out.Bytes())

pkg/providers/v1/aws.go, pkg/providers/v1/aws_utils.go, pkg/providers/v1/aws_utils_test.go
/kind feature
This PR would add additional headers passing the clusters arn and cx account id when making calls to sts  and making calls using an assumed roles.
Fixes #
```release-note
- Add cluster details as headers to STS when assuming a role to make requests.
```
=> Add cluster details to the sts through headers

hack/e2e/run.sh
Same change that we did earlier here:
https://github.com/kubernetes/cloud-provider-aws/commit/2346f203ce325913ef8ed8d19b6283495ae43749#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R23
/kind cleanup
Fixes #
```release-note
NONE
```
=> Reflect community ownership in default image name

pkg/providers/v1/aws.go, pkg/providers/v1/aws_utils.go, pkg/providers/v1/aws_utils_test.go
/kind feature
Cherry pick of #649 
Fixes #
```release-note
- Add cluster details as headers to STS when assuming a role to make requests.
```
=> Add cluster details to the sts through headers 

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
/kind bug
When support was added for `public.ecr.aws` images, a simple `string.Contains` was used to determine whether a requested image reference was a private or public ECR repository. If you use `public.ecr.aws` anywhere in your image reference, such as:
```
123456789123.dkr.ecr.us-west-2.amazonaws.com/public.ecr.aws/foo:latest
```
Then public ECR creds will be retrieved, and image pulls will fail (or you'll fail to call `ecr-public::GetAuthorizationToken` if your IAM creds don't have permissions for it).
Fixes #651
I did some cleanup while I was at it:
- I removed the `RegistryIds` parameter to `GetAuthorizationTokenInput`. This field is …
=> Handle private ECR image references containing public.ecr.aws

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
/kind bug
Removes the graceful handling of `InvalidInstanceID.NotFound` error when attempting to `tag` an ec2 instance that has not fully come up. This has caused an issue where we've seen the tagging controller misleadingly exit successfully, not actually tagging the instance, and does not re-queue the item to (ideally) execute again once the instance becomes visible.
example log feed:
```log
tags.go:326] Couldn't find resource when trying to tag it hence skipping it, InvalidInstanceID.NotFound: The instance ID 'i-***' does not exist status code: 400, request id: ***
tagging_controller.go:299] Successfully tagged i-*** with map[aws:eks:cluster-name:***]. Labeling the nodes with tagging controller labels now. …
```
=> Do not allow EC2 instance ID NotFound to succeed tagging

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Remove ecr pattern restriction and forward region responsability to AWS SDK default behavior. This allow users to use this binary with any registries even they configure properly their AWS SDK (`AWS_REGION` environment variable or any other configuration handled in AWS SDK)  
Fixes #668
```release-note
[ecr-credential-provider] An ECR token is returned for the default AWS region when the specified image reference doesn't …
```
=> Remove ecr pattern restriction

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
Cherry pick of #667 on release-1.28.
#667: Handle private ECR image references containing public.ecr.aws
```release-note
```
=> Automated cherry pick of #667: Handle private ECR image references containing public.ecr.aws

hack/e2e/run.sh
Cherry pick of #557 on release-1.24.
#557: Update kOps command for creating clusters
```release-note
```
=> [release-1.24] Automated cherry pick of #557: Update kOps command for creating clusters

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.28.
```release-note
```
=> [release-1.28] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.25.
```release-note
```
=> [release-1.25] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.24.
```release-note
```
=> [release-1.24] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.27.
```release-note
```
=> [release-1.27] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.26.
```release-note
```
=> [release-1.26] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

hack/e2e/run.sh
kops 1.28 is the last version that supports Kubernetes 1.23; this will fix the CI on release-1.23 and we can merge the pending PR's.
NONE
=> [release-1.23] Pin kops version to 1.28

pkg/controllers/tagging/tagging_controller.go
/kind cleanup
Fix cloud controler manager logs:
> I1101 15:10:22.564856 11 tagging_controller.go:216] Dequeuing latency %!s(float64=0.000102683)
N/A
```release-note
NONE
```
=> fix(controllers/tagging): fix log format string

pkg/providers/v1/tags.go, pkg/providers/v1/tags_test.go
Cherry pick of #674 on release-1.23.
```release-note
```
=> [release-1.23] Automated cherry pick of #674: do not allow ec2 instance ID not found in tagging path

pkg/providers/v1/aws.go, pkg/providers/v1/aws_utils.go, pkg/providers/v1/aws_utils_test.go
/kind feature
Cherry pick of #649 
Fixes #
```release-note
- Add cluster details as headers to STS when assuming a role to make requests.
```
=> [release-1.23] Cherry pick of #649: Add cluster details to the sts through headers

charts/aws-cloud-controller-manager/values.yaml
/kind cleanup
The spurious character was introduced in the initial version of the helm chart.
YAML linters fail with errors similar to:
```
131:16    error    too many spaces before colon  (colons)
```
```release-note
NONE
```
=> Remove spurious space character in helm chart

pkg/controllers/tagging/tagging_controller.go
/kind cleanup
**What this PR does / why we need it**: Similar to https://github.com/kubernetes/cloud-provider-aws/pull/712, fix logging format.
> I1107 17:47:44.958671 11 tagging_controller.go:250] Processing latency %!s(float64=0.565427747)
should be "Processing latency 0.565427747 seconds".
**Special notes for your reviewer**: Thanks.
```release-note
NONE
```
=> fix(pkg/controllers/tagging): correct logging message for seconds

.github/workflows/deps.yml, .ko.yaml, Dockerfile, cloudbuild.yaml
/kind cleanup
Update the go version to 1.21.4 to fix the CVE https://www.cve.org/CVERecord?id=CVE-2023-45283
https://pkg.go.dev/vuln/GO-2023-2185
```release-note
Updated GO version to  1.21.4 to fix CVE-2023-45283 
```
=> Update the go version to 1.21.4

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
This avoids unnecessary retries for invalid Node events (the corresponding EC2 instance does not exist). When many Nodes are created and deleted, the event queue of the tagging controller can grow, causing delays in handling valid events. Every node is "retried" on each update event -- this PR tries to avoid repeated attempts to process a single event when possible.
If the Node is newly-created, we requeue the event and retry, to handle eventual-consistency of the EC2 CreateTags API. If the Node is not newly-created, we drop the event.
Fixes #
```release-note
NONE
```
=> Drop Node event when EC2 instance does not exist

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Cherrypick 1.26: Drop Node events when EC2 instance does not exist and node is not new

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
Fixes #
```release-note
NONE
```
=> Cherrypick 1.27: Drop Node events when EC2 instance does not exist and node is not new

.github/workflows/deps.yml, .ko.yaml, Dockerfile, cloudbuild.yaml
>
> /kind bug
> /kind design
> /kind flake
update go version to fix the failure in govlun check.
Logs of a failed govlun check: https://github.com/kubernetes/cloud-provider-aws/actions/runs/7167984447/job/19515167548?pr=763
```release-note
NONE
```
=> update go version to 1.21.5

pkg/controllers/tagging/tagging_controller.go
/kind feature
This enables all the internal workqueue metrics. They're registered to the `legacyregistry` as the existing metrics in the tagging controller are.
Fixes #
I changed the name of the `workqueue` instance. Before this change, I don't think this is really being exposed in any way, so shouldn't matter.
```release-note
The tagging controller's `workqueue`now registers its internal metrics.
```
=> Enable prometheus provider for workqueue metrics

.github/workflows/helm_chart_release.yaml, .github/workflows/tag.yml
This PR is made under Kubernetes Security Slam.
This resolve the Token Permissions Check fail issue found in CLOMonitor for the project
> /kind bug
#775
Fixes #
NONE
=> Changes to set minimum token permissions for the GITHUB_TOKEN in yaml files

.github/workflows/deps.yml, docs/README.md
Trying to fix the dependency review workflow, which is misconfigured for `push` and `workflow_dispatch` events.
Also adds a status badge for this workflow to the README, and removes the "contributions welcome" bade, which I think is clutter. Also fixes the href for the go report card to link to the actual report, not the status badge.
Fixes #
```release-note
NONE
```
=> Fix dependency review workflow

.github/workflows/update-deps.yaml, Makefile, hack/update-deps.sh
Giving the kOps approach a try instead of dependabot: https://github.com/kubernetes/kops/blob/b801315e2d06762ab0b827d09c5fb31af351c132/.github/workflows/update-deps.yml
Fixes #
```release-note
NONE
```
=> Add update-deps workflow

hack/install-e2e-tools.sh
/kind bug
CI is broken for release-1.23 branch because of a change in the kubetest2-kops deployer. This pins it to the last-working commit.
Example failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/cloud-provider-aws/798/pull-cloud-provider-aws-e2e/1739308772402139136
Fixes #
```release-note
NONE
```
=> [release-1.23] Pin kubetest2-kops to last-working commit

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
/kind bug
>
> /kind bug
> /kind design
> /kind flake
The controller gets subnets by the order of subnet ids everytime when it ensures NLB, and modifies the worker node SG rules according to subnet CIDRs. This may cause issue under some use case for existing NLBs. For example, if there's an existing NLB-a on subnet-3 and subnet-4, later the user adds new subnets, say subnet-1 and subnet-2, the controller will get subnet-1 and subnet-2 when ensure NLB-a, remove the SG rule on subnet-3 and subnet-4 and add new SG rule on subnet-1 and subnet-2 for the NLB-a, while the NLB-a is still on …
=> use subnets of ensured NLBs when update worker node SG rules

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
Fixes #
```release-note
NONE
```
=> Cherrypick 1.23: Drop Node events when EC2 instance does not exist and node is not new

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
Fixes #
```release-note
NONE
```
=> Cherrypick 1.24: Drop Node events when EC2 instance does not exist and node is not new

pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/tags.go
/kind bug
Fixes #
```release-note
NONE
```
=> Cherrypick 1.25: Drop Node events when EC2 instance does not exist and node is not new

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.23: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.24: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.25: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.28: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.27: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.26: use subnets of ensured NLBs when update worker node SG rules

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go
>
> /kind bug
> /kind design
> /kind flake
see #763 
Fixes #
```release-note
NONE
```
=> Cherrypick 1.29: use subnets of ensured NLBs when update worker node SG rules

docs/prerequisites.md, pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
This adds support for RHEL based distributions that typically use a FQDN.
>
/kind bug
> /kind design
> /kind flake
Backport to fix resource based naming instances
Fixes #799
```release-note
Backport to release 1.26 for resource based named instances
```
=> Backport to release 1.26 - fix: handle subnets with resource based naming more flexibly

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Fixes #
```release-note
NONE
```
=> Cherrypick 1.25 ignore invalid providerid for cache indexer

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Fixes #
```release-note
NONE
```
=> Cherrypick 1.26 ignore invalid providerid for cache indexer

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Fixes #
```release-note
NONE
```
=> Cherrypick 1.24 ignore invalid providerid for cache indexer

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Fixes #
```release-note
NONE
```
=> Cherrypick 1.23 ignore invalid providerid for cache indexer

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go
Fixes #
```release-note
NONE
```
=> Cherrypick 1.27 ignore invalid providerid for cache indexer

pkg/providers/v1/aws.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go
/kind cleanup
/kind feature
The InstancesV2 interface is the path forward for cloud providers. To enable new changes, [like providing custom labels](https://github.com/kubernetes/kubernetes/pull/123223), we need to migrate to InstancesV2 as they won't be implemented in the original Instances interface.
This change is needed to prepare to support #300 
N/A
I've added unit tests here and the automation should run. I'll do some manual testing with an EKS cluster, but if you have suggestions on things I should test specifically, let me know.
```release-note
Migrate to InstancesV2 interface
```
=> Implements InstancesV2 interface

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/instances_v2_test.go, pkg/providers/v1/zones.go, pkg/providers/v1/zones_test.go
/kind cleanup
To support labeling nodes with zone IDs #300, we'll need to map zone names to zone IDs, which isn't readily available in existing calls to generate the instance metadata. When we call `DescribeAvailabilityZones` today to get that information, we don't actually cache that data and just call the API again despite the fact that the data we need (zone name, ID and type) will never change. The only scenario where we can't rely entirely on cached information is when new zones are made available to the account via getting access to a special zone (i.e. local-zone) or AWS adds a new AZ to a region, so we need to refresh values that we can't find.
This PR updates the code to pull zones from a cache before greatly …
=> Get zone information from cache

pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go, pkg/providers/v1/well_known_labels.go, pkg/providers/v1/zones.go, pkg/providers/v1/zones_test.go, tests/e2e/nodes.go
/kind feature
As part of 1.30, [we added the ability to add custom labels from the cloud provider to nodes](https://github.com/kubernetes/kubernetes/pull/123223), and AWS customers are looking for a way to label nodes with a zone ID, which will be consistent across account. That label is added here.\
Fixes #300
Added a new e2e case for this change.
```release-note
Label nodes with zone-id topology label. AWS customers can use the `topology.k8s.aws/zone-id`
label on their nodes to associate observations across AWS accounts in a consistent way.
```
=> Add zone-id topology label to nodes

go.mod, go.sum
>
> /kind bug
> /kind design
> /kind flake
Updates google.golang.org/protobuf to v1.33.0 to resolve [CVE-2024-24786](https://github.com/advisories/GHSA-8r3f-844c-mc37).
- Bump github.com/golang/protobuf to v1.5.4, google.golang.org/protobuf to v1.33.0
**Which issue(s) this PR fixes**: 
Fixes # [CVE-2024-24786](https://github.com/advisories/GHSA-8r3f-844c-mc37)
```release-note
Updates google.golang.org/protobuf to v1.33.0 to resolve CVE-2024-24786
```
=> Bump github.com/golang/protobuf v1.5.4, google.golang.org/protobuf v1.33.0

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
/kind bug
This ensures that the addresses associated with network devices attached to the host are added to a Node resource's address list in order of device index.  For some unknown reason AWS returns the list of network devices for just some of our EC2 instances where the primary device is not first in the list.  Without this code change, the addresses of the secondary devices are listed first in the addresses for a Node, and this breaks the ability to interact with pods on the node, such as fetching logs and creating port forwards, because the apiserver always uses the first address of the Node resource to reach the kubelet but is unable to reach kubelet on any of these other addresses.
**Which issue(s) this PR …
=> Ensure that addresses are added in network device index order

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
Cherry pick of #909 on release-1.30.
#909: Ensure that addresses are added in network device index order
```release-note
```
=> Automated cherry pick of #909: Ensure that addresses are added in network device index order

charts/aws-cloud-controller-manager/values.yaml
Co-Authored-By: Eric Wolak <eric.wolak@reddit.com>
/kind bug
This PR adds  to the RBAC configuration for the `system:serviceaccount:kube-system:cloud-controller-manager` by granting ability to create tokenreviews and subjectaccessreviews. This update enables the service account to validate client credentials allowing Prometheus to scrape metrics.
This fix came up while trying to utilize cloud-controller-manager metrics. While trying to get prometheus to authenticate with the `cloud-controller-manager` metrics port, we found that the `serviceaccount:kube-system:cloud-controller-manager` does not have the right RBAC to perform authentication and …
=> Grant cloud-controller-manager RBAC permissions for HTTP port access

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
Cherry pick of #981 on release-1.27.
#981: add support for new aws partitions in credential provider
```release-note
```
=> Automated cherry pick of #981: add support for new aws partitions in credential provider

pkg/providers/v1/aws_sdk.go
/kind cleanup
Formats the instance metadata log message properly such that its easier to look for the details.
Before : `instance metadata identityregionus-west-2availability-zoneus-west-2ainstance-typem5.largearchitecturex86_64instance-idi-0b0e5f62cc663a8b9private-ip172.16.59.42account-idxxxximage-idami-089dfc7e6aaa02c83`
After : `instance metadata identity" region="us-west-2" availability-zone="us-west-2a" instance-type="m5.large" architecture="x86_64" instance-id="i-0b0e5f62cc663a8b9" private-ip="172.16.59.42" account-id="xxx" image-id="ami-089dfc7e6aaa02c83`
Fixes #
```release-note
NONE
```
=> format the instance metadata details log

.ko.yaml, Dockerfile, cloudbuild.yaml, go.mod, pkg/providers/v1/aws.go, tests/e2e/go.mod
/kind bug
If the RegisterInstancesWithLoadBalancer fails for any reason during an LoadBalancer Update call, we do not throw the error and return nil. So we will never know if the target group registration passes or fails
For testing - 
I tried to mock the ELB API as I wasn't able to hit the throttling every time. 
I introduced a 50% chance of ELB API failing to register the target using Mocked return message 
```
val := rand.Int()
if val%2 != 0 {
klog.V(1).Infof("Not using Mocked call %s", loadBalancerName)
_, err = c.elb.RegisterInstancesWithLoadBalancer(registerRequest)
} else {
klog.V(1).Infof("Using Mocked call %s", loadBalancerName)
err = fmt.Errorf("mocked throttled call")
}
if err != nil {
return err
} …
```
=> Handle error while registering/deregistering target during load balancer update calls

pkg/providers/v1/aws.go
Cherry pick of #997 on release-1.29.
#997: Handle error while registering/deregistering target during
```release-note
```
=> Automated cherry pick of #997: Handle error while registering/deregistering target during

charts/aws-cloud-controller-manager/templates/daemonset.yaml, charts/aws-cloud-controller-manager/values.yaml
**What type of PR is this?** /kind feature
Requirement is to specify credentials for pulling image from private registry. 
Allows user to specify imagepullsecret
Fixes #
NONE
release-note:
```release-note
Allow user to specify imagePullSecrets 
```
=> Allow user to specify Registry Pull Secret

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go
/kind bug
This PR updates the load balancer security group update logic for ELBs so that we can actually delete a security group when there is an untagged group present.
In the current flow, we can add rules to the security group if it is untagged, but we cannot remove them since the logic excludes untagged groups from the `actualGroups` list. When we are deleting the load balancer and deleting the security group, we need to make sure that we remove all rules that refer to the security group else the security group deletion will reach a dependency violation deadlock.
To ensure compatibility with BYO security groups, the code ensures that we only pass the `isDeleting` parameter as true when the existing logic determines …
=> Ensure removal of security group rules on deleting load balancers

.ko.yaml, Dockerfile, cloudbuild.yaml, go.mod, pkg/providers/v1/aws_sdk.go, tests/e2e/go.mod
Fixes #1027
/kind bug
```release-note
Fixes an issue introduced in v1.31.0 where a fatal error occurs when AWS_EC2_METADATA_DISABLED is true`
```
=> Make metadata logging best-effort

.ko.yaml, Dockerfile, cloudbuild.yaml, go.mod, pkg/providers/v1/aws_sdk.go, tests/e2e/go.mod
Cherry pick of #1028 on release-1.31.
#1028: Make metadata logging best-effort
```release-note
Fixes an issue introduced in v1.31.0 where a fatal error occurs when AWS_EC2_METADATA_DISABLED is `true`
```
=> Automated cherry pick of #1028: Make metadata logging best-effort

docs/prerequisites.md, pkg/providers/v1/aws.go, pkg/providers/v1/aws_ec2.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/iface/types.go, pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go, pkg/providers/v1/topology.go, pkg/providers/v1/topology_test.go, pkg/providers/v1/well_known_labels.go, tests/e2e/nodes.go
/kind feature
This PR is to Add network topology information to nodes for #998.
Fixes #998
I'm taking over #1025 because the author left on vacation and I'm continuing her work to get this merged.
```release-note
Label nodes with network topology labels. AWS customers can use the `topology.k8s.aws/network-node-layer-N`
labels on their nodes to schedule workloads in close network proximity to each other.
```
=> Add network topology information to nodes (continued)

Makefile, pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_sdk.go
/kind cleanup
I'm going to continue work on the AWS SDK v2 migration, and I saw code related to autoscaling groups, which we don't actually use for anything here, so I just removed it.
N/A
```release-note
NONE
```
=> Removes unused autoscaling code

pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go, pkg/resourcemanagers/topology.go, pkg/resourcemanagers/topology_test.go
/kind bug
The existing change doesn't work for Fargate nodes because they don't get filtered out appropriate when getting instance topology because they don't exist in EC2. If there are any other non-standard nodes that are actually handled gracefully, they'll fail as well.
N/A
```release-note
NONE
```
=> Gracefully handles getting instance topology and unhandled variants

pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go, pkg/resourcemanagers/topology.go, pkg/resourcemanagers/topology_test.go
/kind bug
[Fixes issue described here.](https://github.com/kubernetes/cloud-provider-aws/pull/1060)
N/A
```release-note
NONE
```
=> Cherry picks gracefully handles getting instance topology and unhandled variants in 1.30

pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go, pkg/resourcemanagers/topology.go, pkg/resourcemanagers/topology_test.go
/kind bug
[Fixes issue described here.](https://github.com/kubernetes/cloud-provider-aws/pull/1060)
N/A
```release-note
NONE
```
=> Cherry picks gracefully handles getting instance topology and unhandled variants in 1.31

Makefile, hack/install-ko.sh
/kind bug
CI jobs are broken because we were using an ancient version of `google/ko` that has a broken dependency chain:
```
> make ko-build-local
hack/install-ko.sh
go: downloading github.com/google/ko v0.11.2
go: github.com/google/ko@v0.11.2: version constraints conflict:
github.com/google/ko@v0.11.2 indirectly requires nhooyr.io/websocket@v1.8.7: reading nhooyr.io/websocket/go.mod at revision v1.8.7: unknown revision v1.8.7
```
Results in:
```
Error response from daemon: No such image: ko.local:v1.30.0-beta.0-110-gac63fea
The push refers to repository [209411653980.dkr.ecr.us-east-1.amazonaws.com/provider-aws/cloud-controller-manager]
An image does not exist locally with the tag: …
```
=> Update to latest ko

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
/kind feature
This PR modifies the ECR Registry Regex to add support to new up and coming ECR Dual Stack endpoints. These endpoints are in the format: 
```
<account_id>.dkr-ecr.<region>.on.aws
<account_id>.dkr-ecr.<region>.on.amazonwebservices.com.cn
<account_id>.dkr-ecr-fips.<region>.on.aws
```
This PR also cleans up the `parseRegionFromECRPrivateHost` function to expect 5 capture groups from the `ecrPrivateHostPattern` regex that would be of interest within the code. 
Example input: `123456789123.dkr-ecr-fips.us-west-2.on.aws`
Captures:
- 0 -123456789123.dkr-ecr-fips.us-west-2.on.aws (Entire match)
- 1 - 123456789123 (Account ID)
- 2 - -fips (Fips endpoint)
- 3 - us-west-2 (region)
- 4 - on.aws (Domain)
Testing was …
=> Update ECR Regex to support new dual stack endpoints + tests

cmd/ecr-credential-provider/main.go, cmd/ecr-credential-provider/main_test.go
Cherry pick of #1069 on release-1.29.
#1069: Update ECR Regex to support new dual stack endpoints, modify
```release-note
```
=> Automated cherry pick of #1069: Update ECR Regex to support new dual stack endpoints, modify

pkg/providers/v1/aws.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_test.go, pkg/providers/v1/config/config.go
/kind bug
When a service is using the default configuration (ie they haven't changed any of port, path or protocol via annotations), this updates the health check to, rather then checking the traffic port, check the kube-proxy health endpoint.
This is deliberately done so that if a user has specified any change to the port/path/protocol, we do not change the behaviour of their health checks. But if they have no opinion at all, we give them an improved health check.
[KEP 3458](https://github.com/kubernetes/enhancements/issues/3458) was added to the AWS provider in release 1.27. This means now that a nodes presence in the load balancer backends, is no longer determined by whether the …
=> Update health checks to use Kube-Proxy when no other configuration is provided

pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go
/kind bug
The tagging controller can add the same node multiple times to the workqueue since the node is updated frequently by the kubelet if the add event for that node is not processed yet. This is because for the workqueue add we are not adding an object which is different for each event. When a large number of nodes are added at a time, the queue can become so big that it can take hours/days for all the events to be handled.
Removed the time and retry count from the workqueue object as they are provided by default by the workqueue library and made the workqueue object simple such that multiple add/updates to a node will only add one item to the workqueue.
Fixes #
**Special notes for …
=> optimize tagging controller workqueue handling

pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go
Cherry pick of #1091 on release-1.32.
#1091: optimize tagging controller workqueue handling
```release-note
```
=> Automated cherry pick of #1091: optimize tagging controller workqueue handling

cmd/ecr-credential-provider/main.go
/kind bug
This log line is in the wrong place, should be when `region == ""` not `region != ""`.
Noticed in #1029 
```release-note
NONE
```
=> ecr-credential-provider: Fix warning about no region in image ref

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go
/kind feature
Currently, we make multiple ```ec2:DescribeInstances``` API calls to populate various fields in InstanceMetadata. This PR consolidates multiple API calls into a single request per instance, aiming to improve node join latency.
No functional changes; the behavior remains the same, with fewer ec2:DescribeInstances API calls.
=> Optimize node controller describe instances calls

pkg/providers/v1/aws.go, pkg/providers/v1/aws_fakes.go, pkg/providers/v1/instances_v2.go, pkg/providers/v1/instances_v2_test.go
Cherry pick of #1109 on release-1.32.
#1109: Optimize node controller describe instances calls
```release-note
```
=> Automated cherry pick of #1109: Optimize node controller describe instances calls

.ko.yaml, Dockerfile, cloudbuild.yaml, go.mod, tests/e2e/go.mod
/kind cleanup
Bump go-runner base image to >= 1.23.1 to address CVE: 
> https://nvd.nist.gov/vuln/detail/CVE-2024-34156
Fixes #
```release-note
NONE
```
=> Bump go runner to v2.3.1-go1.23.2-bookworm.0

pkg/controllers/options/tagging_controller.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go, pkg/controllers/tagging/tagging_controller_wrapper.go
/kind feature
* Tagging controller currently operates as a single-threaded process, leading to a backlog when processing nodes in larger clusters. PR introduces ```tagging-controller-concurrent-node-syncs``` option, allowing multiple parallel workers to pull from the work queue.
* Testing with 1,000 nodes at a concurrency level of 10, over 50% of the nodes are tagged in under 1 second. In contrast, with single concurrency, 90% of the nodes take between 1 to 10 seconds to be tagged.
```release-note
A new command-line flag, `tagging-controller-concurrent-node-syncs`, allows more than one node to be processed at once.
```
=> Enable concurrent workers for tagging controller

pkg/controllers/tagging/metrics.go, pkg/controllers/tagging/tagging_controller.go, pkg/controllers/tagging/tagging_controller_test.go
>
> /kind flake
Adds tagging controller delays metric. This measure the delay between node-creation and tagging of the EC2 Instance. The metrics should show up like so:
```
inital_node_tagging_delay_seconds [ALPHA] Latency (in seconds) between node creation and its first successful tagging by TaggingController.
tagging_controller_inital_node_tagging_delay_seconds_bucket{le="1"} 0
tagging_controller_inital_node_tagging_delay_seconds_bucket{le="4"} 0
tagging_controller_inital_node_tagging_delay_seconds_bucket{le="16"} 0
tagging_controller_inital_node_tagging_delay_seconds_bucket{le="64"} 0
tagging_controller_inital_node_tagging_delay_seconds_bucket{le="256"} 0 …
```
=> feat: add tagging controller delays and work queue size metrics

pkg/controllers/tagging/tagging_controller.go
/kind feature
The tagging controller log's are quite chatty, and this can cause issues in large clusters.
Fixes #
```release-note
NONE
```
=> fix: reduce log verbosity of tagging controller

.github/workflows/kpromo-reminder.yaml
>
/kind cleanup
Adds a github workflow that will remind contributors to release new versions.
This should help avoid issues where artifacts are unavailable.
```release-note
NONE
```
=> Add kpromo reminder workflow for releases

pkg/providers/v1/aws.go
/kind cleanup
Isolating security group deletion fragments from `EnsureLoadBalancerDeleted` to `buildSecurityGroupsToDelete` and `deleteSecurityGroupsWithBackoff`, so the evaluation criteria and backoff deletion can be reused in future implementations, i.e. NLB with Security Groups.
This change contributes to decrease the change scope of https://github.com/kubernetes/cloud-provider-aws/pull/1158.
Only the backoff logic has been changed to add exponencial check, preventing 
Fixes #
```release-note
NONE
```
=> refact/lb/sg: isolate security group deletion fragments from EnsureLoadBalancerDeleted

pkg/providers/v1/sets_ippermissions.go, pkg/providers/v1/sets_ippermissions_test.go
/kind bug
The Difference method calculation are returning wrong values on service update calculating the security group rules.
The core issue is caused by it is always comparing the pointer address, not the values, always generating difference between lists.
Example:
given s1:{a1, a2} and s2:{a2,a3,a4}
s2.Difference(s1) was returning {a2, a3, a4}, instead {a3, a4}
Fixes #1206
```release-note
Fixed security group rule difference calculation comparing pointers instead of values, 
eliminating failures on rule updates.
```
=> fix/lb SG rule update failures when service port is changed

pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_loadbalancer_test.go
>
/kind bug
> /kind design
> /kind flake
Fixes a nil pointer dereference introduced by the SDK Go V2 migration in https://github.com/kubernetes/cloud-provider-aws/pull/1157.
The SDK migration's nil pointer dereference issue is in [pkg/providers/v1/aws_loadbalancer.go:ensureSSLNegotiationPolicy](https://github.com/kubernetes/cloud-provider-aws/pull/1223/files#diff-70a4ebdf516a65404dc3c3b3ba9925fc62d0f85bd75e272a4f8ddb4b7b8ab852R1515), and is due to the SDK Go V2 returning nil on error rather than an empty struct. So, when the code didn't return an error and continued into the code, …
=> Remove potential nil ptr dereferences

pkg/providers/v1/aws_fakes.go, pkg/providers/v1/aws_loadbalancer.go, pkg/providers/v1/aws_loadbalancer_test.go
Cherry pick of #1223 on release-1.32.
#1223: remove nil ptr dereference
```release-note
```
=> Automated cherry pick of #1223: remove nil ptr dereference

pkg/providers/v1/topology.go, pkg/providers/v1/topology_test.go
>
/kind bug
> /kind design
> /kind flake
Adds `p6e-gb200` and `p6-b200` to matching regexp for instances that support DescribeInstanceTopology API, and should block node initialization.
updates values overall based on latest in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-topology-prerequisites.html
Fixes #
```release-note
NONE
```
=> fix: update instance types requiring topology labels

pkg/providers/v1/sets_ippermissions.go, pkg/providers/v1/sets_ippermissions_test.go
Cherry pick of #1207 on release-1.33.
#1207: fix: rule difference for nested objects
```release-note
```
=> Automated cherry pick of #1207: fix: rule difference for nested objects

pkg/providers/v1/topology.go, pkg/providers/v1/topology_test.go
Cherry pick of #1230 on release-1.32.
#1230: fix: update instance types requiring topology labels
```release-note
NONE
```
=> Automated cherry pick of #1230: fix: update instance types requiring topology labels

pkg/providers/v1/describe_instance_batch.go, pkg/providers/v1/instances_v2_test.go
/kind bug
Fix the describe instance batcher when the instance is not found or the batch call return error. If the instance is not found we shouldn't be returning an array of empty object but should be returning a nil. This is causing CCM to panic when the nodes deletion in apiserver is blocked because of finalizers but the instance in the aws is deleted. This bug is introduced in the https://github.com/kubernetes/cloud-provider-aws/pull/1152
Fixes #
```release-note
```
=> Fix the batched describe insance method for instance not found case

.ko.yaml, Dockerfile, cloudbuild.yaml, go.mod, tests/e2e/go.mod
Cherry pick of #1266 on release-1.34.
#1266: bump go sdk to 1.24.7 for CVE
```release-note
```
=> Automated cherry pick of #1266: bump go sdk to 1.24.7 for CVE
