- OWNERS
Signed-off-by: Nick Turner <nic@amazon.com>
> Add myself, Micah to approvers/reviewers

- SECURITY_CONTACTS
> Create SECURITY_CONTACTS file

- SECURITY_CONTACTS
Add new team members who are the primary maintainers from the AWS side.
/kind feature
/sig aws
/release-note-none
> Add AWS team as security contacts

- NOTICE
- THIRD-PARTY-LICENSES
/kind feature
/sig aws
/release-note-none
> Add NOTICE and third-party attribution

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/failing-test.md
- .github/ISSUE_TEMPLATE/support.md
- .github/PULL_REQUEST_TEMPLATE.md
Copied from kubernetes as a starting point for this repo.
/kind feature
/sig aws
/release-note-none
> Add GitHub templates

- Dockerfile
found a few issues in my earlier pull #70 .
1. theres a Makefile in this project, so we should use it to build. the version variable usage in the ld flags was taken as a literal due to single quotes. 
2. for some reason, there is an issue with the AWS credentials when using the scratch image. using the distroless image works fine. i tried creating a bunch of paths and copying files to see which one being missing was causing the issue but i was unable to figure it out.
heres the error that occurs when using scratch on startup.
```
I0108 21:51:36.763010       1 aws.go:1112] Using AWS assumed role arn:aws:iam::XXX:role/kube
I0108 21:51:36.763042       1 aws.go:1183] Building AWS cloudprovider
I0108 21:51:36.763110       1 aws.go:1149] Zone not specified in configuration file; querying AWS …
```
> change dockerfile to distroless, use make

- .github/PULL_REQUEST_TEMPLATE.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update error link
```
> add sig-release

- OWNERS
/kind cleanup
Adds myself to OWNERS.
```release-note
NONE
```
> add myself to OWNERS

- README.md
Similar to #82 - if you copy the node role to the IAM console, the JSON errors, and you need to unindent. 
>
> /kind bug
> /kind design
> /kind flake
Extension of another PR (82) to fix the node role 
NONE
> Fix JSON for node role in README

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Fix PR 103, which fixes a broken link.  This removes an extraneous file inadvertently added to the PR.
Fixes #77 
```release-note
NONE
```
> Fixed broken link

- manifests/aws-cloud-controller-manager-daemonset.yaml
/kind feature
Bump the image version in the example manifest to use new version.
Fixes #
```release-note
Bump the image version in the example manifest to use v1.18.0-alpha.1
```
> bump image version in example manifests to v1.18.0-alpha.1

- README.md
Un-indent the opening brace of the controller IAM policy. Use two spaces
per indent in the node IAM policy, as it is in the controller policy.
Clean up some trailing whitespaces. Do not use trailing empty lines in
code blocks, do add them before the next heading.
Signed-off-by: Matthias Rampke <matthias@rampke.de>
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cosmetically change the examples in the README. This is not strictly necessary but the inconsistency annoyed me enough to make this PR.
none
**Does this PR …
> Clean up whitespace in README

- Dockerfile
/kind bug
fixes Dockerfile to add files in /pkg folder
Fixes Dockerfile
```release-note
NONE
```
> Fix Dockerfile to add files in /pkg folder

- Dockerfile
- manifests/aws-cloud-controller-manager-daemonset.yaml
>
/kind cleanup
Merge master into release-1.19
Fixes #
```release-note
NONE
```
> Merge master into release-1.19

- Dockerfile
- go.mod
/kind cleanup
bump the go version to v1.15 latest
Fixes #
```release-note
Bump the go version to v1.15 latest
```
> Bump the go version to v1.15 latest

- Makefile
/kind bug
Fixes the env vars for the build command.
Fixes #158
```release-note
NONE
```
> Fix build command

- cloudbuild.yaml
/kind bug
Fixes cloudbuild
Fixes #
```release-note
NONE
```
> Fix cloudbuild image name

- OWNERS
Matthew is an owner of the AWS CSI drivers and has contributed
extensively to k/k and the CSI drivers. He will be contributing
to the external cloud provider as well as providing reviews and
approvals.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Add wongma7 to owners

- charts/aws-cloud-controller-manager/Chart.yaml
- charts/aws-cloud-controller-manager/LICENSE
- charts/aws-cloud-controller-manager/Readme.md
- charts/aws-cloud-controller-manager/templates/NOTES.txt
- charts/aws-cloud-controller-manager/templates/_helpers.tpl
- charts/aws-cloud-controller-manager/templates/cluserrolebinding.yaml
- charts/aws-cloud-controller-manager/templates/clusterrole.yaml
- charts/aws-cloud-controller-manager/templates/daemonset.yaml
- charts/aws-cloud-controller-manager/templates/rolebinding.yaml
- charts/aws-cloud-controller-manager/templates/serviceaccount.yaml
- charts/aws-cloud-controller-manager/values.yaml
/kind feature
Helm Chart For AWS Cloud Controller Manager.
Fixes #119
NONE
```release-note: Helm Chart For AWS Cloud Controller Manager.
```
> feat: Helm chart for aws cloud controller manager

- go.mod
- go.sum
>
/kind feature
* updates klog library from 2.4.0 to 2.5.0
Fixes #
```release-note
NONE
```
> update klog library from 2.4.0 to 2.5.0

- .github/workflows/release.yaml
- .gitignore
- CHANGELOG.md
- docs/RELEASE.md
- hack/changelog.py
- mkdocs.yml
Mainly for adding the release process, but I also changed the structure of the docs little bit. Now we have tabs for "User Guide", "Development" and "Changelog".  Example: https://ayberk.github.io/cloud-provider-aws/
Fixes #142
```release-note
NONE
```
> Document release process

- charts/aws-cloud-controller-manager/Chart.yaml
- charts/aws-cloud-controller-manager/values.yaml
- docs/CHANGELOG.md
- docs/README.md
- manifests/aws-cloud-controller-manager-daemonset.yaml
I updated the docs with the wrong version after the last release. This fixes it.
```release-note
NONE
```
> Fix version

- docs/README.md
Signed-off-by: Pavel Malinov <pmmalinov01@gmail.com>
Fix a broken link to the KEP
Fixes #
NONE
```release-note
Fix broken link to KEP
```
> Fixing broken KEP link

- .gitignore
- Makefile
/kind feature
Adds a new target to build the credential provider binary for Windows. 
```release-note
NONE
```
> Add Makefile target for windows binary

- docs/getting_started.md
I hope this will save other people's time...
It improves the quality of the documentation.
Fixes #
A to-do list to be able to run AWS cloud-controller-manager on a k8s cluster.
Thanks for your time...
NONE
```release-note
NONE
```
> A missing item

- docs/CHANGELOG.md
>
Update changelog for v1.21.0-alpha.0.
Fixes #
```release-note
NONE
```
> Changelog 1.21

- docs/CHANGELOG.md
Release 1.22
```release-note
NONE
```
> Changelog v1.22.0-alpha.0

- Dockerfile
- go.mod
/kind feature
Keeping up with go releases and it's nice to get a better view into the indirect deps with the new go.mod format.
https://go.dev/doc/go1.17#graph-pruning
n/a
Kubernetes already moved to go 1.17 in https://github.com/kubernetes/kubernetes/pull/103692.
```release-note
NONE
```
> Update go to v1.17.4

- go.mod
- go.sum
/kind feature
Updates aws-sdk-go to the latest version.
This adds new features like DualStack endpoints:
https://github.com/aws/aws-sdk-go/releases/tag/v1.42.0
n/a
n/a
```release-note
Updates aws-sdk-go to v1.42.20
```
> Update aws-sdk-go to v1.42.20

- .github/workflows/helm_chart_release.yaml
- docs/CHANGELOG.md
- docs/README.md
- docs/RELEASE.md
>
Release v1.23.0-alpha.0
```release-note
NONE
```
/cc @wongma7
> Release v1.23.0-alpha.0

- pkg/providers/v1/aws.go
Cherry pick of #313 on release-1.22.
#313: add sts regional endpoint logic
```release-note
```
> Automated cherry pick of #313: add sts regional endpoint logic

- charts/aws-cloud-controller-manager/templates/daemonset.yaml
- charts/aws-cloud-controller-manager/values.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Follow from #328. In case the OIDC provided requires different audience, an additional volume projected serviceAccountToken is required which needs to be mounted. Example
```yaml
extraVolumeMounts:
- mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount/"
name: aws-token
extraVolumes:
- name: aws-token
projected:
sources:
- serviceAccountToken:
audience: "sts.amazonaws.com"
expirationSeconds: 86400
path: token
```
Fixes #327 
**Does this PR introduce a user-facing …
> chart: Add extraVolumes and extraVolumeMounts

- docs/CHANGELOG.md
- docs/README.md
>
* update changelog and readme
```release-note
NONE
```
> Update changelog and readme with v1.23.0 and v1.24.0-alpha.0

- cloudbuild.yaml
Fixes a nit noticed during #352 code review.
Ref: https://github.com/kubernetes/cloud-provider-aws/pull/352#discussion_r869192683
/cc @justinsb @nckturner
> Explain short tag with comment

- Dockerfile
>
> /kind bug
> /kind design
/kind feature
> /kind flake
After #330, updating the Go images used in builds is the next step.
n/a
n/a
```release-note
NONE
```
> Update Go to v1.18.1

- docs/CHANGELOG.md
- hack/changelog.py
Changelog for v1.24.0 and v1.23.1
```release-note
NONE
```
> Release v1.24.0

- OWNERS
> Add olemarkus to owners file

- cloudbuild.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes promotion to staging of build artifacts.
Refs: https://github.com/kubernetes/cloud-provider-aws/pull/365
After https://github.com/kubernetes/cloud-provider-aws/pull/308, `cloudbuild.yaml` needs to be updated also.
```release-note
NONE
```
> Update cloud build config for v1.21

- cloudbuild.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes promotion to staging of build artifacts.
Refs: https://github.com/kubernetes/cloud-provider-aws/pull/365
After https://github.com/kubernetes/cloud-provider-aws/pull/205, `cloudbuild.yaml` needs to be updated also.
```release-note
NONE
```
> Update cloud build config for v1.20

- cloudbuild.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
`latest` tag when pushing images to staging should only be applied on `master` branch
n/a
n/a
```release-note
NONE
```
> Stop tagging latest for release branches

- OWNERS
```release-note
NONE
```
/cc @olemarkus @nckturner 
/assign @nckturner
> Add hakman to owners file

- examples/kops-new-cluster/base/cluster.yaml
- examples/kops-new-cluster/overlays/cloud-controller-manager/cluster.yaml
- hack/kops-example.sh
/kind cleanup
```release-note
Update the `kops-test.sh` script to work with newer kOps versions.
```
> Fix the kops-example script

- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_loadbalancer.go
- pkg/providers/v1/instances.go
- pkg/providers/v1/volumes.go
- pkg/providers/v2/instances.go
/kind cleanup
Fix gofmt
Fixes #
```release-note
NONE
```
> Update gofmt for go 1.19

- hack/e2e/run.sh
Fix e2e tests with temporary fix.
Modify location of kops binary based on where it actually gets installed.
Fixes #
```release-note
NONE
```
> E2E tests fix

- charts/aws-cloud-controller-manager/values.yaml
/kind feature
node-role.kubernetes.io/master taint/labels are deprecated, and are bing deprecated in favour of node-role.kubernetes.io/control-plane. Same goes for nodeSelector
None
```release-note
action required - In order to use the default nodeSelector and toleration, make sure your control plane nodes are labelled accordingly. To use the old master labels, set in your values file: `nodeSelector` to `node-role.kubernetes.io/master: ""`
```
> control plane tolerations/selector

- charts/aws-cloud-controller-manager/Chart.yaml
/kind feature
Bump helm chart version so it gets properly released.
Just a chart bump
NONE
> Bump helm chart version

- netlify.toml
/kind cleanup
Fixed docs generation.
n/a
n/a
```release-note
NONE
```
> Bump netlify Python for to v3.8

- go.mod
- go.sum
/kind cleanup
Bump on to aws-sdk-go v1.44.107
```release-note
NONE
```
> update aws-sdk-go to v1.44.107

- Dockerfile
> Update Go to v1.19.3

- .ko.yaml
- Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update golang base image to v 1.19.4
Fixes #
```release-note
NONE
```
> update base image to golang 1.19.4

- docs/credential_provider.md
The changed line is currently rendering on the site as - 
> So ".io" does not match ".k8s.io".
Fixes #
```release-note
NONE
```
> docs: use backticks to preserve wildcard chars

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
> Add kishorj to the owners file

- hack/e2e/run.sh
>
> /kind bug
> /kind design
> /kind flake
This is cherry-pick of https://github.com/kubernetes/cloud-provider-aws/pull/553
Fixes #
```release-note
NONE
```
> Update kOps command for creating clusters

- OWNERS
Will start helping out in this repository (long time contributor to sig-cloud-provider and have working on removing in-tree cloud providers from k/k)
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> Add dims to OWNERS file

- docs/README.md
This PR updates README with the latest cloud-provider-aws release tags for k8s versions 1.20-1.24 and adds the latest release tags for versions 1.25-1.26
Fixes # None
**Special notes for your reviewer**: NONE
**Does this PR introduce a user-facing change?**: NONE
> Update README with latest releases

- Dockerfile
- docs/RELEASE.md
/kind bug
This PR will update the uses of deprecating `k8s.gcr.io` registry to `registry.k8s.io` prior to the planned April freeze.
Fixes # https://github.com/kubernetes/k8s.io/issues/4738
Search results: https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/cloud-provider-aws
```release-note
NONE
```
> Update registry k8s.gcr.io -> registry.k8s.io

- cloudbuild.yaml
> Fetch tags for later use when running cloudbuild

- Makefile
> Upload artifacts before generating the checksums

- docs/getting_started.md
- examples/kops-new-cluster/base/cluster.yaml
- examples/kops-new-cluster/overlays/cloud-controller-manager/kustomization.yaml
- hack/kops-example.sh
Fixes the read me links and also the kops example.
Fixes #
```release-note
NONE
```
> Update Readme and fix the kops cluster create example

- cloudbuild.yaml
/kind cleanup
- Migrate away from google.com gcp project k8s-testimages
- format indentation
- also match the same golang version that is used in the project
Related to https://github.com/kubernetes/k8s.io/issues/1523
/assign @ameukam @dims @justinsb
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
```release-note
NONE
```
> Migrate away from google.com gcp project k8s-testimages 

- OWNERS
I'd like to help out here as a reviewer (not approver at this time). There's some PR's that need love. 😄 
Fixes #
```release-note
```
> Add cartermckinnon as a reviewer

- docs/credential_provider.md
We've received questions about how the ECR cred provider authenticates. This adds some brief docs on it.
No
> Add authentication section to cred provider docs

- charts/aws-cloud-controller-manager/templates/daemonset.yaml
- charts/aws-cloud-controller-manager/values.yaml
>
Ability to specify pod annotations in templates.
Fixes #
NONE
NONE
```release-note
```
> Add template annotations to daemonset

- cmd/aws-cloud-controller-manager/main.go
https://github.com/kubernetes/cloud-provider-aws/pull/641 introduced a bug where the controller alias map has the wrong value for the tagging controller:
```
"tagging" is not in the list of known controllers
Error: "tagging" is not in the list of known controllers
```
This PR will fix the issue. I have tested it in my cluster and it was able to start the cloud controller manager successfully.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE …
```
> Update tagging controller's alias

- docs/getting_started.md
- examples/existing-cluster/base/aws-cloud-controller-manager-daemonset.yaml
- examples/existing-cluster/base/cluster-role.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
> Fix url to reflect current directory structure / fix image tag version

- charts/aws-cloud-controller-manager/Chart.yaml
- charts/aws-cloud-controller-manager/values.yaml
/kind feature
This commit actualize latest release version in helm chart
> Bump Chart and appVersion

- Makefile
- hack/switch-to-latest-k8s.sh
We can generate a fresh tar prepped to test using:
```
hack/switch-to-latest-k8s.sh && make ko-build-tar
```
- We assume kubernetes is checked out under $GOPATH/src/k8s.io/kubernetes
- We update the daemonset as well with the latest version number
In the test harness, if we run the command above and copy over the directory with the manifests to the control plane node, we can load the image to containerd and then use the updated manifests to deploy the freshly built aws cloud controller manager.
/kind feature
Fixes #
```release-note
NONE
```
> Script to test with latest k8s

- Makefile
Adding a new `test-e2e-latest-k8s` which runs the `./hack/switch-to-latest-k8s.sh` before running e2e-tests
This target will be used in [`ci-cloud-provider-aws-e2e-with-kubernetes-master` CI job](https://cs.k8s.io/?q=ci-cloud-provider-aws-e2e-with-kubernetes-master)
> Add new Makefile target to be able run CI jobs compiling the external cloud provider with latest k8s

- hack/e2e/run.sh
Hmm, are way outdated. let's switch to newer versions of k8s
/kind cleanup
Fixes #
```release-note
NONE
```
> Always run against latest kubernetes version

- OWNERS
N/A
I've been involved in the repo for a while and am now part of the k8s org
N/A
NONE
> Update OWNERS to include mmerkes as a reviewer

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.23] Add hakman, cartermckinnon

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.28] Add cartermckinnon to approvers

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.27] Add cartermckinnon

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.24] Add cartermckinnon

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.26] Add cartermckinnon

- OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
> [release-1.25] Add cartermckinnon

- .ko.yaml
- Dockerfile
- cloudbuild.yaml
Bump the go version and go runner version
> update the go version to 1.21.3

- OWNERS
- SECURITY_CONTACTS
/kind cleanup
cc @jaypipes @dims can you both +1?
Fixes #
```release-note
NONE
```
> Removed emeritus reviewers from SECURITY_CONTACTS

- pkg/controllers/tagging/tagging_controller.go
- pkg/controllers/tagging/tagging_controller_test.go
- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_fakes.go
- pkg/providers/v1/tags.go
/kind bug
N/A
```release-note
NONE
```
> Cherypick 1.28: Drop Node events when EC2 instance does not exist and node is not new

- .github/dependabot.yaml
Adds a basic dependabot configuration for the default branch. I've limited the bot to 3 PR's at a time, and it will only run weekly. If this goes well, we can add config for the other release-* branches.
Fixes #
```release-note
NONE
```
> Add dependabot configuration for default branch

- .github/dependabot.yaml
Sets labels on the dependabot PR's so they automatically test, and do not require a release note (doesn't seem to be a way to automate this by appending a `release-note` block to the PR description).
Fixes #
```release-note
NONE
```
> Set labels for dependabot PR's, remove gomod rule

- docs/README.md
This gets rid of the version table from the README. We don't want to update this every time a release is cut on any of the active branches, and the compatibility is already clearly explained in the text.
https://github.com/kubernetes/cloud-provider-aws/issues/799#issuecomment-1869759028
Fixes #
```release-note
NONE
```
> Remove version matrix from README

- .github/workflows/helm_chart_release.yaml
/kind feature
No idea what kind to choose for CI-related tooling.
**What this PR does / why we need it**: 
Right now helm releases are marked as "Latest release" on GitHub and are shown on the main repo page next to the readme. However people don't really care about the latest helm version, but the latest release of the cloud provider, so we release helm without setting it as latest.
None
NONE
> Stop marking helm releases as "Latest release"

- hack/tag-release.sh
>
> /kind bug
> /kind design
> /kind flake
Support rc tag, otherwise current tag release will fail for rc tag like https://github.com/kubernetes/cloud-provider-aws/actions/runs/8458955184/job/23174283151
Fixes #
```release-note
NONE
```
> Support rc tag

- OWNERS
Moves a set of owners to emeritus that haven't been active in this repo for a while.
/kind cleanup
As part of updating the owners, I'm cleaning up some folks that haven't contributed to this repo in a while. I will wait for them to confirm that it's safe to remove them, or that I should keep them on the list.
N/A
@justinsb @M00nF1sh @andrewsykim I don't see any recent activity from you, so I proposed moving you to the emeritus status. If you're good with that, +1 this PR. If you're still contributing and think access should be left as is, just comment and I'll remove you! I wasn't able to figure out how to see comment/approval history...
**Does this …
> Moving OWNERS to emeritus

- .github/workflows/deps.yml
- .github/workflows/update-deps.yaml
- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
>
> /kind bug
> /kind design
> /kind flake
Bumping go version to 1.22.2
Fixes #
```release-note
NONE
```
> bumping go to 1.22.2

- .github/workflows/deps.yml
- .github/workflows/update-deps.yaml
- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
- tests/e2e/go.mod
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
N/A
N/A
```release-note
NONE
```
> Go version workflows

- docs/overrides/partials/copyright.html
- mkdocs.yml
Adds correct trademark disclaimer, as part of our ongoing effort to https://github.com/cncf/techdocs/issues/198
Fixes #837
```release-note
NONE
```
> docs(footer): Add trademark disclaimer

- .github/workflows/deps.yml
- .ko.yaml
- Dockerfile
- cloudbuild.yaml
go1.21.11 has some security fixes - https://go.dev/doc/devel/release#go1.21.11
/kind bug
Fixes #
```release-note
NONE
```
> Bump golang version to 1.21.11 for release-1.29 branch

- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
go1.22.4 has some security fixes - https://go.dev/doc/devel/release#go1.22.4
/kind bug
Fixes #
```release-note
NONE
```
> Bump golang version to 1.22.4 for release-1.30 branch

- pkg/controllers/tagging/tagging_controller.go
- pkg/controllers/tagging/tagging_controller_test.go
- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_fakes.go
- pkg/providers/v1/aws_instance.go
- pkg/providers/v1/aws_loadbalancer_test.go
- pkg/providers/v1/aws_sdk.go
- pkg/providers/v1/aws_test.go
- pkg/providers/v1/config/config.go
- pkg/providers/v1/iface/types.go
- pkg/providers/v1/instances.go
- pkg/providers/v1/tags.go
- pkg/providers/v1/tags_test.go
- pkg/providers/v1/variant/fargate/fargate.go
- pkg/providers/v1/variant/variant.go
Cherry pick of #917 on release-1.30.
#917: extract fargate into a standalone file
```release-note
NONE
```
> Automated cherry pick of #917: extract fargate into a standalone file

- OWNERS
> Add kmala to the owners file

- OWNERS
> [release-1.29] Add kmala to the owners file

- OWNERS
> [release-1.30] Add kmala to the owners file

- OWNERS
> [release-1.28] Add kmala to the owners file

- OWNERS
> [release-1.27] Add kmala to the owners file

- OWNERS
> [release-1.26] Add kmala to the owners file

- OWNERS
> [release-1.25] Add kmala to the owners file

- OWNERS
> [release-1.24] Add kmala to the owners file

- OWNERS
> [release-1.23] Add kmala to the owners file

- cmd/ecr-credential-provider/main.go
- cmd/ecr-credential-provider/main_test.go
/kind feature
Allow credential provider to recognize new aws partitions.
Fixes #
```release-note
NONE
```
> add support for new aws partitions in credential provider

- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_sdk.go
Helps if we know who we are talking to (apiserver info!) and where we are running (node/identity info!) in the logs themselves.
/kind cleanup
Fixes #
```release-note
NONE
```
> Log useful information about the cluster and the instance

- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
- hack/e2e/run.sh
- tests/e2e/go.mod
/kind cleanup
Addresses govulncheck vulnerabilities with go version and project dependencies
Fixes #
```release-note
```
> Bump go mod version

- docs/development.md
> /kind flake
Just clean up the development.md guide.
N/A
None
```release-note
NONE
```
> Fixes typo and formatting in development.md

- pkg/controllers/tagging/tagging_controller.go
/kind cleanup
Since k8s 1.31, a few client-go types including rate-limitter have onboarded to golang generics which is available for golang 1.18+. This PR switches the controller to use the generic types from k8s.io dependencies.
**Special notes for your reviewer**: Trivial cleanups
```release-note
NONE
```
> Use typed client-go constructors for rate-limit related objects

- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
- tests/e2e/go.mod
>
> /kind bug
> /kind design
> /kind flake
Update go version to 1.24.4
Fixes #
```release-note
NONE
```
> update go version to 1.24.4

- THIRD-PARTY-LICENSES
- go.mod
- go.sum
- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_fakes.go
- pkg/providers/v1/aws_instance.go
- pkg/providers/v1/aws_loadbalancer.go
- pkg/providers/v1/aws_loadbalancer_test.go
- pkg/providers/v1/aws_routes.go
- pkg/providers/v1/aws_test.go
- pkg/providers/v1/instances.go
- pkg/providers/v1/instances_test.go
- pkg/providers/v1/instances_v2_test.go
- pkg/providers/v1/retry_handler.go
- pkg/providers/v1/sets_ippermissions.go
- pkg/providers/v1/sets_ippermissions_test.go
- pkg/providers/v1/tags.go
- pkg/providers/v1/tags_test.go
- pkg/providers/v1/variant/fargate/fargate.go
- pkg/providers/v1/zones.go
- pkg/providers/v1/zones_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This PR updates usage of the `aws` and `awserr` packages in the AWS SDK for Go from V1 to their V2 equivalents. 
The AWS SDK Go V1 is being deprecated on July 31, 2025. This PR migrates usage of the EC2 SDK to use V2.
Context: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
Continues work on upgrading repo to AWS SDK Go V2. (PR 1: https://github.com/kubernetes/cloud-provider-aws/pull/1146, PR 2: https://github.com/kubernetes/cloud-provider-aws/pull/1157 PR 3: #1169). 
**Which issue(s) …
> Update aws & awserr packages to AWS SDK Go V2

- .ko.yaml
- Dockerfile
- cloudbuild.yaml
- go.mod
- tests/e2e/go.mod
Cherrypick #1135 to release 1.33
```release-note
None
```
> Cherrypick #1135 to release 1.33

- pkg/providers/v1/aws.go
- pkg/providers/v1/aws_fakes.go
- pkg/providers/v1/aws_sdk.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Removes the unused autoscaling client from the repo. 
Fixes #
NONE
```release-note
Removes unused Autoscaling SDK client.
```
> Cleanup unused autoscaling client

- OWNERS
/assign @kmala 
-->
```release-note
NONE
```
> Adding yue9944882 to eks team approver

- docs/development.md
Enhancing the developer documentation helping the user to run existing cluster in non-standard distribution to quickly ramp-up the experience testing changes in existing clusters locally.
Fixes #
Contributing with the development documentation with steps I needed to test in non-standard environment.
```release-note
Enhance development documentation with steps to run the controller locally.
```
> doc/devel: enhance docs to use in existing cluster

- charts/aws-cloud-controller-manager/Chart.yaml
/kind cleanup
Followup to https://github.com/kubernetes/cloud-provider-aws/pull/1211
missed bumping other chart values.
Fixes #
```release-note
```
> chore(chart): update version

- charts/aws-cloud-controller-manager/Chart.yaml
- charts/aws-cloud-controller-manager/values.yaml
/kind feature
This PR is to update cloud-controller-manager image version from v1.33.0 to latest v1.34.0 in the helm chart. Also bump the helm chart version and appversion. 
Fixes #
```release-note
Update cloud-controller-manager image version to v1.34.0
```
> Update cloud-controller-manager image version to v1.34.0
